# Generated by Django 4.2.2 on 2023-06-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_category_alter_stamp_title_stamp_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stamp',
            old_name='content',
            new_name='price',
        ),
    ]
