# Generated by Django 4.2.2 on 2023-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_rename_content_stamp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
