# Generated by Django 4.2.2 on 2023-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0005_alter_category_options_alter_stamp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamp',
            options={'ordering': ['-in_stock', 'title'], 'verbose_name': 'Топ марки', 'verbose_name_plural': 'Топ марки'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
