# Generated by Django 4.2.2 on 2023-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0007_alter_category_slug_alter_stamp_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(db_index=True, max_length=100, verbose_name='Новини')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
                'ordering': ['id'],
            },
        ),
    ]
