# Generated by Django 4.2.2 on 2023-06-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0008_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, verbose_name='Вміст новини'),
        ),
    ]
